### ISSUE TITLE
Specs confusing?

### ISSUE THREAD

**Issue by cktricky** [OWASP/railsgoat#166]
This one I'm not clear about but we received feedback that specs were "fixed" when they should fail and pending when they were fixed.

This could actually be the result of poor documentation on the subject because this is a new complaint we've not yet received.

**Comment by chrismo** [comment]
Overall it'd be nice to have a much more straightforward way of doing this. I settled on the way it is now to try and aid BOTH the end-user and the maintainer, but ... it leaves it weird for the end-user. Maybe some more custom magicks could be put into play -- I largely leaned on whatever was already there in rspec and pending - but ... it sorta sucks.

**Comment by cktricky** [comment]
Fwiw, @geeksam initially had made mention of the specs issue this was created for, maybe he'd have more insight or recommendations?

**Comment by geeksam** [comment]
Hmm.  It's been a couple of months since I tried to go through the tutorial, and I'm not sure if I kept my notes when I changed jobs.  At a minimum, the output from RSpec is confusing, and the text of the tutorial should be much more explicit about what to expect.  That's not ideal, though, because having to remember that "up is down" imposes a cognitive load on the end user who's going through a tutorial, which means they have less brainpower available to solve the problem and thus actually learn something.

(Actually, if there was a single unifying theme to my various complaints about the tutorial, it's that the actual end-user experience seemed never to have been considered.  I realize it's hard to approach this stuff with beginner's mind when you wrote it, but a bit of what Joel Spolsky calls "hallway usability testing" might be informative.  But I digress...)

As I recall, I lost some time re-familiarizing myself with the "pending" behavior and what it meant.  Compounding the issue, I think the behavior changed between RSpec 2.x and 3.x, which probably wouldn't have been a problem for a new RSpec user, but threw me off.

If the same set of tests needs to be run and interpreted differently by end users and maintainers, perhaps something clever could be done with rspec metadata attached to each spec?  (That would also allow the end user to focus on a single spec for the duration of an exercise, which I often find helps reduce distractions.)  Perhaps even something like the way Cucumber behaves in 'wip mode'...

**Comment by cktricky** [comment]
Great feedback!

As for better documentation, I'm working through that with a new tutorial flow and @chrismo is helping identify broken / missing code or tutorial pieces. This way getting started and using Railsgoat is *generally* less of hassle.

I've found it confusing as well since failed = fixed in the verbiage, as an example:

![screen shot 2015-01-09 at 2 31 04 pm](https://cloud.githubusercontent.com/assets/544667/5685832/2e8d742c-980c-11e4-855d-00b63ee0be27.png)

The tutorials will need to be linked to a spec (part of this joint effort) and I'll take charge on introducing & enforcing a new rule for the project -  "a new vuln must ship with both a tutorial and spec."

**Comment by cktricky** [comment]
oh and thanks! @geeksam

**Comment by jmmastey** [comment]
@ctricky suggestion:

I tried reversing the logic on one of the spec files: https://gist.github.com/jmmastey/9f04ef9cc4919546a41fbbce46171446

I think this is an improvement for users, and it's not much worse for the maintainers. Basically, the user gets a bunch of red tests that she is responsible for turning green. No extra `pending` markers in the tests themselves, and the normal sort of "make this green" semantics are preserved.

For maintainers, using the maintainer flag causes the pending behavior (and still fails if the tests don't work, as originally designed).

If you agree that this is a better format for users, I'd be down to change them.

**Comment by chrismo** [comment]
@jmmastey i like the idea! can you show it in a PR so I can easily glance at the diff?

**Comment by jmmastey** [comment]
@chrismo here's the diff from just that first change:

https://github.com/OWASP/railsgoat/compare/master...jmmastey:invert-specs?expand=1

**Comment by cktricky** [comment]
Went back thru, re-read all of the comments of this issue, and reviewed your proposed fix in order to (re)understand what we're trying to solve. I think your proposed solution is great, and may solve some of the "huh?" factor when newcomers try running their tests.
