### ISSUE TITLE
When BCrypt solution is put in place, the password is stored plaintext?

### ISSUE THREAD

**Issue by chrismo** [OWASP/railsgoat#186]
Not 100% that this isn't my fault for how I'm solving things, but I tweaked the solution with this additional line to set password to nil
```
  def hash_password
    if self.password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(self.password, self.password_salt)
      self.password = nil
    end
  end
```
though in a real app you wouldn't even keep the password column in the table.

**Comment by cktricky** [comment]
Right, and in the "video tutorial platform" who I won't mention by name
because this is an OWASP project, we show how to implement this in the
Rails A6 video but I'm not sure it made it into this tutorial so def
something that needs to be shored up. Here is a code snippet from that
video tutorial:

$ rails g migration RemovePasswordFromUsers password:string
$ rails g migration AddPasswordHashAndSaltToUsers password_hash:text
password_salt:text

**Comment by cktricky** [comment]
Updated the wiki to remove that column as per this conversation.
