### ISSUE TITLE
pending semantics changed in rspec 3.0 and now getting a lot more output for RAILSGOAT_MAINTAINER='yes' rake'

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#294]
**pending** semantics changed in rspec 3.0 and now getting a lot more output for **RAILSGOAT_MAINTAINER='yes' rake'**

Attached a file with sample output: [o_rmr.txt](https://github.com/OWASP/railsgoat/files/1604045/o_rmr.txt)

This includes many **Failure/Error:** stack traces.

**Comment by jasnow** [comment]
@cktricky - Is this expected output?

**Comment by cktricky** [comment]
This is the expected output after PR #291. The output shows 7 functional tests passing and 14 security tests pending.

The output is a bit lengthy but if you take, as an example, #14 - the reason for pending makes sense:

```
  14) unvalidated redirect attack
Tutorial: https://github.com/OWASP/railsgoat/wiki/A10-Unvalidated-Redirects-and-Forwards-(redirect_to)
      # No reason given
      Failure/Error: expect(current_url).to eq("/dashboard/home")

        expected: "/dashboard/home"
             got: "http://example.com/do/evil/things"

```

When the redirect attack works, and the user is not redirected to `/dashboard/home` and instead is sent to `http://example.com/do/evil/things` then we still have a security test failing (and since its in maintainer mode, *pending*).

Hopefully all that makes sense, its still relatively early 😄

**Comment by mccabe615** [comment]
@jmmastey is there a way to limit the output then add a verbose flag to get more output? This is a lot for a new user to parse when running these tests, though it's useful for debugging once you get the issue.

**Comment by jmmastey** [comment]
A lot of the output is "page contains X" stuff, so that might be a good place to start.

Otherwise, the text is coming from stacktrace spam. One thought would be to dig into the RSpec error reporter a little bit and use something like this:

http://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html

Another idea would be to teach students to use `fit` (focus mode) to fix one test at a time as part of the docs.

Thoughts on any of these?

**Comment by jasnow** [comment]
Check out the **Changes to pending semantics (and introduction of skip)** at http://rspec.info/blog/2014/05/notable-changes-in-rspec-3. We stayed at rspec 2.99 for a long time because of the special pending usage in this repo - we lose pending's **old "never run" behaviour** which prevented the code from triggering.

**Comment by jasnow** [comment]
I have the fix. I will push it as a PR after today's gem upgrade PR is approved and merged.

**Comment by jmmastey** [comment]
@cktricky what are your thoughts on the PR @jasnow put up?

**Comment by cktricky** [comment]
Sorry, circling back. So is the problem the amount of output because of the stacktrace or the tests staying in pending mode?

If its the first, I'd agree, we can make that easier to grok.

The pending mode is a bigger challenge because, here is what we're trying to accomplish

Maintainers:

1) Tests that verify functionality is still... functional
2) Vulnerabilities are still... vulnerabilities

Students

1) Vulnerabilities are fixed or not

We have no need to duplicate Item 2 for Maintainers and Item 1 for students - so we combined them. 

---

I keep going back and forth between separating the tests and combining them because, I think mainly because I'm just confused on what the actual problem statement is. If the tests fail, they won't be in pending, they'll fail. So if 14 are pending and 7 are passing, we know 👍 . Am I missing something? (seriously asking)

**Comment by jasnow** [comment]
@cktricky, @mccabe615 
Here is a copy of the railsgoat repo (I saved) before applying the 4Q's changes:
 * https://github.com/jasnow/railsgoat17
Now you can compare both modes and study/fix/accept the regression(s).

**Comment by jasnow** [comment]
very old issue so closing it.
