### ISSUE TITLE
Install new version GitHub Slack App

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#330]
[Blog Post](https://github.com/blog/2506-slack-and-github-your-ultimate-productivity-pair) on new version of GitHub Slack App -https://owasp.slack.com/apps/A8GBNUWU8-github

**Comment by jasnow** [comment]
Also: https://github.com/blog/2509-commit-with-confidence-with-new-teacher-training-from-github

**Comment by cktricky** [comment]
I was able to do most of the installation except that I need an owner to install the GitHub Slack App on the OWASP github org so that I can finish the slack subscription. The good news is, once this is done, owners won't get asked by other owasp projects to do the same thing... it will already be installed.

[This is the link](https://github.com/apps/slack/installations/new/permissions?target_id=155815) to install the GitHub Slack App.

/cc owasp org owners @DinisCruz @dancornell @cscasanovas123 @psiinon @thesp0nge

**Comment by jasnow** [comment]
Posted request for help to [OWASP/GSOC Google Group](https://groups.google.com/forum/#!topic/owasp-gsoc/w9zPCaE7WvU) today.

**Comment by cktricky** [comment]
Thanks @jasnow 👍 - now we wait 🕐

**Comment by cscasanovas123** [comment]
Hi Al,

Can I help you with something ?

**Comment by cktricky** [comment]
@cscasanovas123 I'm not sure if OWASP wants to install the GitHub Slack app on all repos but, that is certainly an option. Mainly, this means other projects won't be bugging you (hopefully). The other option is just to install it on our repo. Either way, this is the link: https://github.com/apps/slack/installations/new/permissions?target_id=155815

Thank you 🙇

**Comment by cktricky** [comment]
Big thank you to @jeremylong for helping us out here!

**Comment by jasnow** [comment]
Appears that the app has been installed so closing this issue.
