### ISSUE TITLE
Use Github's "release" feature with RailsGoat.

### ISSUE THREAD

**Issue by jasnow** [OWASP/railsgoat#332]
Use Github's [release](https://github.com/OWASP/railsgoat/releases) feature with RailsGoat.

**Comment by cktricky** [comment]
I've added 3 releases. [rails.3](https://github.com/OWASP/railsgoat/releases/tag/rails.3), [rails.4](https://github.com/OWASP/railsgoat/releases/tag/rails.4), and [rails5.0.0](https://github.com/OWASP/railsgoat/releases/tag/rails.5.0.0). Rails 3/4 I didn't feel we had any need for minor/major versions since we typically don't perform any work on those releases anymore. This is why they're just `rails.3` and `rails.4` However, since the Rails 5 branch (master)_will_ have future releases, I did a version `5.0.0.` to allow for minor/major releases.

If this is sufficient, please close the issue @jasnow. If not, let me know what you'd like changed 👍

**Comment by jasnow** [comment]
LGTM - Closing issue
